#include "lexer.h"
#include "file_io.h"
#include <stdlib.h>
#include <string.h>
#include <stddef.h>

#define MIN_LEX 32

static _lexeme_t* lexeme_marcher(char* line);

// TODO: (integral) make an analyzer that uses a buffer system and check
//      whether a valid lexeme is generated by loading characters into
//      a checking buffer one at a time and calling strcpy() a lot.
// TODO: (integral) research a better way to do this if you aren't going
//      to do the above TODO

_lexeme_t* gen_lexemes(const char * filename) {
    _lexeme_t* lexemes = (_lexeme_t*)malloc(sizeof(_lexeme_t)*MIN_LEX);

    size_t num_lines;
    char** raw_file = get_raw_lines(filename, &num_lines);

    for (size_t i = 0; i < num_lines; i++) 
        lexeme_marcher(raw_file[i]);
    printf("\n");

    return lexemes;
}

static _lexeme_t* lexeme_marcher(char* line) {
    int line_len;
    if ((line_len = strlen(line)) < 0)
        return NULL;
    int lex_buff = 32;
    char* buffer = (char*)malloc(sizeof(char)*lex_buff);
    memset(buffer, '\0', lex_buff);
    
    _lexeme_t* lexemes = (_lexeme_t*)malloc(sizeof(_lexeme_t));
    char seek = *line;
    for (int i=0, bi = 0, li = 0; i<=line_len; i++) {
        if (seek == '\0')
            break;
        if (seek == '\n' || seek == '\r')
            continue;
        if (bi >= lex_buff)
            buffer = (char*)realloc(buffer, lex_buff*=2);
        
        buffer[bi++] = seek;
        seek = line[i+1];
    }
    printf("%s\n", buffer);
    free(buffer);

    return lexemes;
}